# Generated by Django 5.1.7 on 2025-03-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='date_od_issue',
            new_name='date_of_issue',
        ),
    ]
