# Generated by Django 5.1.7 on 2025-03-13 00:44

import apps.registration.mixins
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.registration.mixins.ProxyModelReportMixin, 'registration.intern'),
            managers=[
                ('proxy_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
